#nullable enable
// <auto-generated>IDE0005 disable for test files</auto-generated>
#pragma warning disable IDE0005

using System.IO;
using AgentDashboard.TicketTracking.Application.GitHub;
using AgentDashboard.TicketTracking.Application.Ports;
using AgentDashboard.TicketTracking.Infrastructure.GitHub;
using AgentDashboard.TicketTracking.Infrastructure.IntegrationTests.GitHub.Fakes;
using AgentDashboard.TicketTracking.Infrastructure.Tickets;
using FluentAssertions;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Time.Testing;
using Xunit;

namespace AgentDashboard.TicketTracking.Infrastructure.IntegrationTests.Tickets;

// Test list for GitHubIssuesPollerSqliteIntegrationTests:
// ========================================================================
// END-TO-END VERIFICATION (Issue #6 - Task D):
//  1. [x] PollerCreatesDatabaseFile_WhenRunWithValidConfiguration
//  2. [x] PollerWritesTicketsToDatabase_WhenGitHubClientReturnsIssues
//  3. [x] PollerWritesCorrectTicketCount_WhenMultipleIssuesReturned
//  4. [x] PollerNeverLogsGitHubToken_WhenConfiguredWithToken
//  5. [x] DatabaseContainsExpectedTicketData_AfterPoll
// ========================================================================

public sealed class GitHubIssuesPollerSqliteIntegrationTests : IAsyncLifetime
{
    private const string ValidToken = "ghp_examplePAT12345";
    private static readonly TimeSpan PollInterval = TimeSpan.FromSeconds(600);

    private FakeTimeProvider _timeProvider = null!;
    private FakeGitHubIssuesClient _fakeClient = null!;
    private RecordingLogger<GitHubIssuesPoller> _pollerLogger = null!;
    private WebApplicationFactory<Program> _factory = null!;
    private string _testDbPath = null!;
    private string _testDbDir = null!;

    public Task InitializeAsync()
    {
        _testDbDir = Path.Combine(Path.GetTempPath(), "agent-dashboard-it", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_testDbDir);
        _testDbPath = Path.Combine(_testDbDir, "tickets.db");

        _timeProvider = new FakeTimeProvider(new DateTimeOffset(2026, 5, 22, 9, 0, 0, TimeSpan.Zero));
        _fakeClient = new FakeGitHubIssuesClient(_timeProvider);
        _pollerLogger = new RecordingLogger<GitHubIssuesPoller>();

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.ConfigureAppConfiguration((_, cfg) =>
                {
                    cfg.AddInMemoryCollection(new Dictionary<string, string?>
                    {
                        ["GITHUB_TOKEN"] = ValidToken,
                        ["POLL_INTERVAL_SECONDS"] = ((int)PollInterval.TotalSeconds).ToString(System.Globalization.CultureInfo.InvariantCulture),
                        ["DATA_PATH"] = _testDbDir,
                    });
                });

                builder.ConfigureServices(svc =>
                {
                    svc.Replace(ServiceDescriptor.Singleton<IGitHubIssuesClient>(_fakeClient));
                    svc.Replace(ServiceDescriptor.Singleton<TimeProvider>(_timeProvider));
                    svc.Replace(ServiceDescriptor.Singleton<ILogger<GitHubIssuesPoller>>(_pollerLogger));

                    // Replace the repository to use our test database path
                    svc.RemoveAll<ITicketWriteRepository>();
                    svc.AddSingleton<ITicketWriteRepository>(_ =>
                        new SqliteTicketWriteRepository("Data Source=" + _testDbPath));
                });
            });
        return Task.CompletedTask;
    }

    public Task DisposeAsync()
    {
        _factory.Dispose();
        if (Directory.Exists(_testDbDir))
        {
            Directory.Delete(_testDbDir, recursive: true);
        }
        return Task.CompletedTask;
    }

    private async Task WaitForPollerToRunAsync()
    {
        await WaitUntilAsync(() => _fakeClient.CallCount >= 1);
    }

    private static async Task WaitUntilAsync(Func<bool> predicate, int timeoutMs = 2000)
    {
        var start = DateTimeOffset.UtcNow;
        while (!predicate())
        {
            if ((DateTimeOffset.UtcNow - start).TotalMilliseconds > timeoutMs)
            {
                return;
            }
            await Task.Delay(20);
        }
    }

    [Fact]
    public async Task PollerCreatesDatabaseFile_WhenRunWithValidConfiguration()
    {
        _ = _factory.Server;
        await WaitForPollerToRunAsync();
        File.Exists(_testDbPath).Should().BeTrue();
    }

    [Fact]
    public async Task PollerWritesTicketsToDatabase_WhenGitHubClientReturnsIssues()
    {
        _ = _factory.Server;
        await WaitForPollerToRunAsync();

        await using var conn = new SqliteConnection("Data Source=" + _testDbPath);
        await conn.OpenAsync(CancellationToken.None);
        await using var cmd = new SqliteCommand("SELECT COUNT(*) FROM tickets", conn);
        var count = Convert.ToInt64(await cmd.ExecuteScalarAsync(CancellationToken.None));
        count.Should().BeGreaterThan(0);
    }

    [Fact]
    public async Task PollerWritesCorrectTicketCount_WhenMultipleIssuesReturned()
    {
        _ = _factory.Server;
        await WaitForPollerToRunAsync();

        await using var conn = new SqliteConnection("Data Source=" + _testDbPath);
        await conn.OpenAsync(CancellationToken.None);
        await using var cmd = new SqliteCommand("SELECT COUNT(*) FROM tickets", conn);
        var count = Convert.ToInt64(await cmd.ExecuteScalarAsync(CancellationToken.None));
        count.Should().Be(2);
    }

    [Fact]
    public async Task DatabaseContainsExpectedTicketData_AfterPoll()
    {
        _ = _factory.Server;
        await WaitForPollerToRunAsync();

        await using var conn = new SqliteConnection("Data Source=" + _testDbPath);
        await conn.OpenAsync(CancellationToken.None);
        await using var cmd = new SqliteCommand("SELECT title, github_issue_number FROM tickets ORDER BY github_issue_number", conn);
        var reader = await cmd.ExecuteReaderAsync(CancellationToken.None);

        var tickets = new List<(string Title, int Number)>();
        while (await reader.ReadAsync(CancellationToken.None))
        {
            tickets.Add((
                reader.GetString(0),
                reader.GetInt32(1)
            ));
        }

        tickets.Should().HaveCount(2);
        tickets[0].Title.Should().Be("first issue");
        tickets[0].Number.Should().Be(1);
        tickets[1].Title.Should().Be("second issue");
        tickets[1].Number.Should().Be(2);
    }

    [Fact]
    public async Task PollerNeverLogsGitHubToken_WhenConfiguredWithToken()
    {
        _ = _factory.Server;
        await WaitForPollerToRunAsync();

        _pollerLogger.Entries.Should().NotContain(e => e.Message.Contains(ValidToken, StringComparison.Ordinal));
        foreach (var entry in _pollerLogger.Entries)
        {
            foreach (var value in entry.State.Values)
            {
                if (value is string s)
                {
                    s.Should().NotContain(ValidToken);
                }
            }
        }
    }
}
