// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

using System;
using System.Collections.Generic;
using AgentDashboard.TicketTracking.Application.GitHub;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Boards;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.TestShared.Factories;

namespace AgentDashboard.TicketTracking.Application.UnitTests.GitHub;

public class GitHubBoardMapperTests
{
    private static readonly DateTimeOffset FixedNow = new(2026, 05, 27, 12, 0, 0, TimeSpan.Zero);
    private static readonly string FixedHtmlUrl = "https://github.com/AskmethatFR/agent-dashboard/issues/1";

    // ========================================================================
    // TEST LIST (TDD by Example - Kent Beck's Test List technique)
    // ========================================================================
    //
    // HAPPY PATH:
    // [✓] Map_RecordsWithAllLabels_ToCompleteBoardSnapshot
    // [✓] Map_SingleRecordWithFullLabels_ToSingleTicket
    //
    // STATUS MAPPING:
    // [✓] Map_StatusCreated_ToCreatedColumn
    // [✓] Map_StatusSpecified_ToSpecifiedColumn
    // [✓] Map_StatusInDevelopment_ToInDevelopmentColumn
    // [✓] Map_StatusInReview_ToInReviewColumn
    // [✓] Map_StatusInQa_ToInQaColumn
    // [✓] Map_StatusAwaitingValidation_ToAwaitingValidationColumn
    // [✓] Map_StatusDone_ToDoneColumn
    // [✓] Map_StatusEscalated_ToCreatedColumn_Fallback
    // [✓] Map_RecordWithoutStatus_ToCreatedColumn_Fallback
    //
    // AGENT MAPPING:
    // [✓] Map_AgentPm_ToPmAgent
    // [✓] Map_AgentArchitect_ToArchitectAgent
    // [✓] Map_AgentDevA_ToDevAAgent
    // [✓] Map_AgentDevB_ToDevBAgent
    // [✓] Map_AgentQa_ToQaAgent
    // [✓] Map_AgentSecurity_ToSecurityAgent
    // [✓] Map_RecordWithoutAgent_ToPmAgent_Fallback
    //
    // RETRY MAPPING:
    // [✓] Map_Retry0_ToRetryZero
    // [✓] Map_Retry1_ToRetryOne
    // [✓] Map_Retry2_ToRetryTwo
    // [✓] Map_Retry3_ToRetryThree
    // [✓] Map_RecordWithoutRetry_ToRetryZero_Fallback
    //
    // FRESHNESS:
    // [✓] Map_DoneTicketWithAgeLessThan24h_ToFresh
    // [✓] Map_TicketWithAgeAtWarningThreshold_ToStale
    // [✓] Map_TicketWithAgeBelowWarningThreshold_ToNeutral
    // [✓] Map_DoneTicketWithAgeOver24h_ToNeutral
    //
    // CROSS-REVIEW & ESCALATION:
    // [✓] Map_InReviewStatus_ToCrossReviewTicket
    // [✓] Map_EscalatedStatus_ToEscalatedTicket
    // [✓] Map_InReviewAndEscalated_ToBothFlagsSet
    //
    // BOARD SNAPSHOT VALIDATION:
    // [✓] Return_BoardSnapshotWithAllColumns
    // [✓] Return_BoardSnapshotWithAllAgents
    // [✓] Return_BoardSnapshotWithNoDuplicateTicketIds
    // [✓] Return_EmptyBoardSnapshot_WhenNoRecords
    //
    // ========================================================================

    // -----------------------------------------------------------------------------
    // Happy Path
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_RecordsWithAllLabels_ToCompleteBoardSnapshot()
    {
        var records = new List<GitHubIssueRecord>
        {
            new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Feature A")
            .WithLabels("status:created", "agent:pm", "retry:0")
            .WithCreatedAt(FixedNow.AddHours(-1))
            .WithHtmlUrl("https://github.com/AskmethatFR/agent-dashboard/issues/1")
            .WithUpdatedAt(FixedNow.AddHours(-1))
            .AsOpen()
            .Build(),
            new GitHubIssueRecordBuilder()
            .WithNumber(2)
            .WithTitle("Feature B")
            .WithLabels("status:in-review", "agent:dev-a", "retry:2")
            .WithCreatedAt(FixedNow.AddHours(-2))
            .WithHtmlUrl("https://github.com/AskmethatFR/agent-dashboard/issues/2")
            .WithUpdatedAt(FixedNow.AddHours(-2))
            .AsOpen()
            .Build(),
            new GitHubIssueRecordBuilder()
            .WithNumber(3)
            .WithTitle("Feature C")
            .WithLabels("status:done", "agent:dev-b", "retry:0")
            .WithCreatedAt(FixedNow.AddHours(-12))
            .WithHtmlUrl("https://github.com/AskmethatFR/agent-dashboard/issues/3")
            .WithUpdatedAt(FixedNow.AddHours(-12))
            .AsOpen()
            .Build(),
        };

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(records, FixedNow);

        snapshot.Columns.Should().HaveCount(7);
        snapshot.Agents.Should().HaveCount(6);
        snapshot.Tickets.Should().HaveCount(3);
    }

    [Fact]
    public void Map_SingleRecordWithFullLabels_ToSingleTicket()
    {
        var records = new List<GitHubIssueRecord>
        {
            new GitHubIssueRecordBuilder()
            .WithNumber(42)
            .WithTitle("Implement health check")
            .WithLabels("status:in-development", "agent:dev-a", "retry:1")
            .WithCreatedAt(FixedNow.AddHours(-2))
            .WithHtmlUrl("https://github.com/AskmethatFR/agent-dashboard/issues/42")
            .WithUpdatedAt(FixedNow.AddHours(-2))
            .AsOpen()
            .Build()
        };

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(records, FixedNow);

        snapshot.Tickets.Should().HaveCount(1);
        var ticket = snapshot.Tickets[0];
        ticket.Id.Value.Should().Be(42);
        ticket.Title.Value.Should().Be("Implement health check");
        ticket.AgentId.Value.Should().Be("dev-a");
        ticket.ColumnId.Value.Should().Be("IN_DEVELOPMENT");
    }

    // -----------------------------------------------------------------------------
    // Status Mapping
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_StatusCreated_ToCreatedColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:created")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("CREATED");
    }

    [Fact]
    public void Map_StatusSpecified_ToSpecifiedColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:specified")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("SPECIFIED");
    }

    [Fact]
    public void Map_StatusInDevelopment_ToInDevelopmentColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:in-development")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("IN_DEVELOPMENT");
    }

    [Fact]
    public void Map_StatusInReview_ToInReviewColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:in-review")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("IN_REVIEW");
    }

    [Fact]
    public void Map_StatusInQa_ToInQaColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:in-qa")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("IN_QA");
    }

    [Fact]
    public void Map_StatusAwaitingValidation_ToAwaitingValidationColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:awaiting-validation")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("AWAITING_VALIDATION");
    }

    [Fact]
    public void Map_StatusDone_ToDoneColumn()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:done")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("DONE");
    }

    [Fact]
    public void Map_StatusEscalated_ToCreatedColumn_Fallback()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:escalated")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("CREATED");
    }

    [Fact]
    public void Map_RecordWithoutStatus_ToCreatedColumn_Fallback()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.ColumnId.Value.Should().Be("CREATED");
    }

    // -----------------------------------------------------------------------------
    // Agent Mapping
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_AgentPm_ToPmAgent()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("agent:pm")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("pm");
    }

    [Fact]
    public void Map_AgentArchitect_ToArchitectAgent()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("agent:architect")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("architect");
    }

    [Fact]
    public void Map_AgentDevA_ToDevAAgent()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("agent:dev-a")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("dev-a");
    }

    [Fact]
    public void Map_AgentDevB_ToDevBAgent()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("agent:dev-b")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("dev-b");
    }

    [Fact]
    public void Map_AgentQa_ToQaAgent()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("agent:qa")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("qa");
    }

    [Fact]
    public void Map_AgentSecurity_ToSecurityAgent()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("agent:security")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("security");
    }

    [Fact]
    public void Map_RecordWithoutAgent_ToPmAgent_Fallback()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:created")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.AgentId.Value.Should().Be("pm");
    }

    // -----------------------------------------------------------------------------
    // Retry Mapping
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_Retry0_ToRetryZero()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("retry:0")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Retry.Value.Should().Be(0);
    }

    [Fact]
    public void Map_Retry1_ToRetryOne()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("retry:1")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Retry.Value.Should().Be(1);
    }

    [Fact]
    public void Map_Retry2_ToRetryTwo()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("retry:2")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Retry.Value.Should().Be(2);
    }

    [Fact]
    public void Map_Retry3_ToRetryThree()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("retry:3")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Retry.Value.Should().Be(3);
    }

    [Fact]
    public void Map_RecordWithoutRetry_ToRetryZero_Fallback()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Retry.Value.Should().Be(0);
    }

    // -----------------------------------------------------------------------------
    // Freshness
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_DoneTicketWithAgeLessThan24h_ToFresh()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:done")
            .WithCreatedAt(FixedNow.AddHours(-12))
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow.AddHours(-12))
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Freshness.Should().Be(TicketFreshness.Fresh);
    }

    [Fact]
    public void Map_TicketWithAgeAtWarningThreshold_ToStale()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow.Subtract(Age.WarningThreshold))
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow.Subtract(Age.WarningThreshold))
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Freshness.Should().Be(TicketFreshness.Stale);
    }

    [Fact]
    public void Map_TicketWithAgeBelowWarningThreshold_ToNeutral()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow.AddMinutes(-30))
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow.AddMinutes(-30))
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Freshness.Should().Be(TicketFreshness.Neutral);
    }

    [Fact]
    public void Map_DoneTicketWithAgeOver24h_ToStale()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:done")
            .WithCreatedAt(FixedNow.AddDays(-2))
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow.AddDays(-2))
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        // TicketSnapshot done >24h is stale because age >= 3h threshold
        ticket.Freshness.Should().Be(TicketFreshness.Stale);
    }

    // -----------------------------------------------------------------------------
    // Cross-Review & Escalation
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_InReviewStatus_ToCrossReviewTicket()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:in-review", "agent:dev-a")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.IsInCrossReview.Should().BeTrue();
    }

    [Fact]
    public void Map_EscalatedStatus_ToEscalatedTicket()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:escalated", "agent:dev-a", "retry:3", "escalation-target:pm")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.IsEscalated.Should().BeTrue();
    }

    [Fact]
    public void Map_InReviewAndEscalated_ToBothFlagsSet()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels("status:in-review", "status:escalated", "agent:dev-a", "retry:3", "escalation-target:pm")
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.IsInCrossReview.Should().BeTrue();
        ticket.IsEscalated.Should().BeTrue();
    }

    // -----------------------------------------------------------------------------
    // Board Snapshot Validation
    // -----------------------------------------------------------------------------

    [Fact]
    public void Return_BoardSnapshotWithAllColumns()
    {
        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord>(), FixedNow);

        snapshot.Columns.Should().HaveCount(7);
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("CREATED");
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("SPECIFIED");
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("IN_DEVELOPMENT");
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("IN_REVIEW");
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("IN_QA");
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("AWAITING_VALIDATION");
        snapshot.Columns.Select(c => c.Id.Value).Should().Contain("DONE");
    }

    [Fact]
    public void Return_BoardSnapshotWithAllAgents()
    {
        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord>(), FixedNow);

        snapshot.Agents.Should().HaveCount(6);
        snapshot.Agents.Select(a => a.Id.Value).Should().Contain("pm");
        snapshot.Agents.Select(a => a.Id.Value).Should().Contain("architect");
        snapshot.Agents.Select(a => a.Id.Value).Should().Contain("dev-a");
        snapshot.Agents.Select(a => a.Id.Value).Should().Contain("dev-b");
        snapshot.Agents.Select(a => a.Id.Value).Should().Contain("qa");
        snapshot.Agents.Select(a => a.Id.Value).Should().Contain("security");
    }

    [Fact]
    public void Return_BoardSnapshotWithNoDuplicateTicketIds()
    {
        var records = new List<GitHubIssueRecord>
        {
            new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("A")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build(),
            new GitHubIssueRecordBuilder()
            .WithNumber(2)
            .WithTitle("B")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl("https://github.com/AskmethatFR/agent-dashboard/issues/2")
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build(),
            new GitHubIssueRecordBuilder()
            .WithNumber(3)
            .WithTitle("C")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl("https://github.com/AskmethatFR/agent-dashboard/issues/3")
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build(),
        };

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(records, FixedNow);

        snapshot.Tickets.Select(t => t.Id.Value).Should().OnlyHaveUniqueItems();
    }

    [Fact]
    public void Return_EmptyBoardSnapshot_WhenNoRecords()
    {
        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord>(), FixedNow);

        snapshot.Tickets.Should().BeEmpty();
        snapshot.Columns.Should().HaveCount(7);
        snapshot.Agents.Should().HaveCount(6);
    }

    // -----------------------------------------------------------------------------
    // Age Calculation
    // -----------------------------------------------------------------------------

    [Fact]
    public void Calculate_AgeFromCreatedAt_When_RecordHasCreatedAt()
    {
        var createdAt = FixedNow.AddHours(-5);
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(createdAt)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(createdAt)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.Age.Value.Should().Be(TimeSpan.FromHours(5));
    }

    // -----------------------------------------------------------------------------
    // Thinking Flag
    // -----------------------------------------------------------------------------

    [Fact]
    public void Map_ThinkingFlag_ToFalse_ForAllTickets()
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(1)
            .WithTitle("Test")
            .WithLabels(Array.Empty<string>())
            .WithCreatedAt(FixedNow)
            .WithHtmlUrl(FixedHtmlUrl)
            .WithUpdatedAt(FixedNow)
            .AsOpen()
            .Build();

        var snapshot = GitHubBoardMapper.MapToBoardSnapshot(new List<GitHubIssueRecord> { record }, FixedNow);
        var ticket = snapshot.Tickets[0];

        ticket.IsThinking.Should().BeFalse();
    }
}
