// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

using System.Collections.Generic;
using System.Linq;
using AgentDashboard.TicketTracking.Application.GitHub;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.TestShared.Factories;

namespace AgentDashboard.TicketTracking.Application.GitHub;

// TEST LIST (Issue #6 — AC3/AC4/AC5/AC10) — driven outside-in from the poller use case.
// The user-observable outcome: when label conflicts/absences are detected, the mapper
// surfaces structured warnings (data) that Infrastructure logs; the row is still written.
//
// AC3 — multiple recognized status:* labels:
//   [x] status:in-qa + status:done -> Status==Done, 1 MultipleStatusLabels warning (issue#, both labels, selected)
//   [x] three status labels -> still latest, 1 warning listing all three
// AC4 — no recognized status:* label:
//   [x] zero status labels -> Status==Created, 1 MissingStatusLabel warning (issue#)
//   [x] only-unrecognized status:foo -> Status==Created, 1 MissingStatusLabel warning (issue#)
// AC5 — retry (no warning):
//   [x] retry:1 + retry:3 + retry:2 -> Retry==3, NO warning
//   [x] no retry label -> Retry==0, NO warning
// Happy path:
//   [x] exactly one status + one agent + one retry -> mapped correctly, Warnings EMPTY
public class GitHubIssueToTicketMapperTests
{
    private static MappingResult Map(long number, params string[] labels)
    {
        var record = new GitHubIssueRecordBuilder()
            .WithNumber(number)
            .WithLabels(labels)
            .Build();

        return GitHubIssueToTicketMapper.Map(record);
    }

    [Theory]
    [MemberData(nameof(MultipleStatusLabelCases))]
    public void SelectLatestStatusAndWarnOnMultipleStatusLabels(
        long issueNumber,
        string[] labels,
        TicketStatusValue expectedStatus,
        string expectedSelectedLabel,
        string[] expectedConflictingLabels)
    {
        var result = Map(issueNumber, labels);

        result.Ticket.TicketStatus.Value.Should().Be(expectedStatus);
        result.Warnings.Should().ContainSingle();

        var warning = result.Warnings.Single();
        warning.Kind.Should().Be(MappingWarningKind.MultipleStatusLabels);
        warning.IssueNumber.Should().Be(issueNumber);
        warning.SelectedStatusLabel.Should().Be(expectedSelectedLabel);
        warning.ConflictingStatusLabels.Should().BeEquivalentTo(expectedConflictingLabels);
    }

    public static IEnumerable<object[]> MultipleStatusLabelCases()
    {
        yield return new object[]
        {
            42L,
            new[] { "status:in-qa", "status:done" },
            TicketStatusValue.Done,
            "status:done",
            new[] { "status:in-qa", "status:done" }
        };
        yield return new object[]
        {
            7L,
            new[] { "status:created", "status:in-development", "status:in-review" },
            TicketStatusValue.InReview,
            "status:in-review",
            new[] { "status:created", "status:in-development", "status:in-review" }
        };
    }

    [Theory]
    [MemberData(nameof(MissingStatusLabelCases))]
    public void DefaultToCreatedAndWarnOnMissingStatusLabel(long issueNumber, string[] labels)
    {
        var result = Map(issueNumber, labels);

        result.Ticket.TicketStatus.Value.Should().Be(TicketStatusValue.Created);
        result.Warnings.Should().ContainSingle();

        var warning = result.Warnings.Single();
        warning.Kind.Should().Be(MappingWarningKind.MissingStatusLabel);
        warning.IssueNumber.Should().Be(issueNumber);
    }

    public static IEnumerable<object[]> MissingStatusLabelCases()
    {
        yield return new object[] { 100L, System.Array.Empty<string>() };
        yield return new object[] { 101L, new[] { "status:foo" } };
        yield return new object[] { 102L, new[] { "bug", "agent:dev-a" } };
    }

    [Theory]
    [MemberData(nameof(RetryCases))]
    public void SelectHighestRetryWithoutWarning(string[] labels, int expectedRetry)
    {
        var result = Map(55L, labels);

        result.Ticket.RetryCount.Value.Should().Be(expectedRetry);
        result.Warnings.Should().BeEmpty();
    }

    public static IEnumerable<object[]> RetryCases()
    {
        yield return new object[] { new[] { "status:created", "retry:1", "retry:3", "retry:2" }, 3 };
        yield return new object[] { new[] { "status:created" }, 0 };
    }

    [Fact]
    public void ProduceNoWarningsOnTheHappyPath()
    {
        var result = Map(1L, "status:in-development", "agent:dev-a", "retry:1");

        result.Ticket.TicketStatus.Value.Should().Be(TicketStatusValue.InDevelopment);
        result.Ticket.RetryCount.Value.Should().Be(1);
        result.Warnings.Should().BeEmpty();
    }
}
