// Escalations Inbox — actionable items waiting on human
window.ESCALATIONS = [
  {
    id: "esc_001",
    raisedAt: "2026-05-20 16:11:32",
    raisedBy: "AR",     // Architect raised it (could be DA/DB/AR/PM)
    raisedTo: "human",
    chainOfEscalation: ["DB→AR", "AR→PM", "PM→human"],
    ticket: 455,
    ticketTitle: "CSRF on /api/admin actions",
    sessionId: "s_188f",
    severity: "high",
    category: "QA↔Security conflict",
    summary: "QA and Security disagree on token rotation cadence — Architect could not arbitrate without product input",
    context: [
      "Security wants per-action rotation (every mutating request) to prevent token replay across endpoints.",
      "QA reports per-action rotation breaks 3 existing e2e scenarios that batch admin operations within a single SSE connection — and there's no UX path for the user to refresh mid-batch.",
      "Both reviewers refused to give without explicit product trade-off. Architect arbitration failed: 'this is a product call, not a tech call'.",
    ],
    timeline: [
      { at: "14:32", who: "PM", txt: "ticket refined, sent to spec" },
      { at: "14:48", who: "AR", txt: "spec written, rotation strategy left open" },
      { at: "15:14", who: "DA", txt: "implemented per-batch rotation (Strategy A)" },
      { at: "15:44", who: "QA", txt: "approved functionally" },
      { at: "15:58", who: "SE", txt: "rejected — vulnerable to replay across actions in batch" },
      { at: "16:04", who: "AR", txt: "attempted arbitration — proposed Strategy B (per-action)" },
      { at: "16:09", who: "QA", txt: "rejected Strategy B — breaks 3 scenarios" },
      { at: "16:11", who: "AR", txt: "escalation raised → PM" },
    ],
    options: [
      {
        id: "A",
        title: "Per-batch rotation (favors QA / current UX)",
        pros: ["Existing UX flows unchanged", "Simpler implementation", "QA scenarios pass as-is"],
        cons: ["Token replay possible across actions within a batch", "Security objects: deviates from internal threat model"],
        proposedBy: "DevA",
      },
      {
        id: "B",
        title: "Per-action rotation (favors Security)",
        pros: ["Closes the replay window completely", "Aligns with internal threat model"],
        cons: ["Breaks 3 e2e scenarios", "Requires UX work (mid-batch refresh) — not scoped", "Estimated +2 sessions to rework"],
        proposedBy: "Architect",
      },
      {
        id: "C",
        title: "Per-batch + scope-limited token (compromise)",
        pros: ["Closes replay within a single action scope", "Existing scenarios pass", "Acceptable to both reviewers if UX is willing to add a 60s batch ceiling"],
        cons: ["More complex than A", "Requires changes to token scoping in 2 services"],
        proposedBy: "Architect (compromise)",
      },
    ],
    waitingFor: "human pick: A, B, or C — or new constraint",
    waitingSinceMin: 31,
  },
  {
    id: "esc_002",
    raisedAt: "2026-05-20 00:26:14",
    raisedBy: "DA",
    raisedTo: "human",
    chainOfEscalation: ["DB→DA", "DA→AR", "AR→PM", "PM→human"],
    ticket: 463,
    ticketTitle: "fix refresh-token replay vulnerability",
    sessionId: "s_17ab",
    severity: "high",
    category: "max retries reached",
    summary: "DevB rejected DevA's implementation 3x in a row — fundamental disagreement on token rotation point in request lifecycle",
    context: [
      "DevA implemented post-response rotation; DevB insists on pre-response rotation for correctness.",
      "Both reviewers argue the existing code style supports their interpretation.",
      "No spec disambiguates — Architect was not available to arbitrate (next session 09:14 today).",
    ],
    timeline: [
      { at: "May 19 14:22", who: "DA", txt: "implement v1 (post-response)" },
      { at: "May 19 16:38", who: "DB", txt: "review rejected — pre-response required" },
      { at: "May 19 19:01", who: "DA", txt: "implement v2 (kept post-response, added comment)" },
      { at: "May 19 21:14", who: "DB", txt: "review rejected — same reason" },
      { at: "May 19 22:48", who: "DA", txt: "implement v3 (changed minor) — pleaded for clarification" },
      { at: "May 20 00:18", who: "DB", txt: "review rejected — 3/3 reached" },
      { at: "May 20 00:26", who: "DA", txt: "escalation raised through chain → human" },
    ],
    options: [
      {
        id: "A",
        title: "Force-merge DevA's v3 (post-response)",
        pros: ["Unblocks the loop", "Aligns with the only working test suite available"],
        cons: ["Overrides DevB's review — sets precedent", "May leave a latent correctness issue"],
        proposedBy: "DevA",
      },
      {
        id: "B",
        title: "Discard branch, re-spec with Architect arbitration",
        pros: ["Resolves the disagreement at the right layer", "Architect available since 09:14 today"],
        cons: ["~1 day lost", "Vulnerability remains open in prod meanwhile"],
        proposedBy: "Architect",
      },
      {
        id: "C",
        title: "Pair-implement: both DevA and DevB on a fresh branch with shared spec",
        pros: ["Forces alignment", "Architect can guide spec live"],
        cons: ["Most expensive (3 sessions)"],
        proposedBy: "PM",
      },
    ],
    waitingFor: "human decision — security fix is blocking release v2.4",
    waitingSinceMin: 1037,
  },
  {
    id: "esc_003",
    raisedAt: "2026-05-19 15:42:08",
    raisedBy: "QA",
    raisedTo: "human",
    chainOfEscalation: ["QA→AR", "AR→PM", "PM→human"],
    ticket: 441,
    ticketTitle: "migrate logger to pino, structured JSON output",
    sessionId: "s_169e",
    severity: "medium",
    category: "ambiguous acceptance criteria",
    summary: "Spec said 'preserve human-readable output in dev mode' — implementation does, but QA test scenarios assume strict JSON in all environments",
    context: [
      "Spec ambiguity: 'preserve human-readable' vs QA's 'verify JSON parseable end-to-end'.",
      "DevA's implementation toggles format by NODE_ENV; QA tests run in dev (human-readable), so they fail.",
      "Architect: 'spec is genuinely ambiguous, this is a product call on what the acceptance contract is'.",
    ],
    timeline: [
      { at: "May 18 19:01", who: "QA", txt: "validation failed — JSON not parseable in dev" },
      { at: "May 19 09:14", who: "AR", txt: "spec re-read, ambiguity confirmed" },
      { at: "May 19 15:42", who: "AR", txt: "escalation → PM" },
    ],
    options: [
      {
        id: "A",
        title: "Update QA scenarios to skip JSON check in dev",
        pros: ["Preserves human-readable dev experience"],
        cons: ["QA loses end-to-end JSON verification"],
        proposedBy: "DevA",
      },
      {
        id: "B",
        title: "Force JSON everywhere, drop human-readable",
        pros: ["Consistent output, simpler tests"],
        cons: ["Worse local dev ergonomics"],
        proposedBy: "QA",
      },
    ],
    waitingFor: "human pick — what's the acceptance contract?",
    waitingSinceMin: 1560,
  },
];

window.ESCALATION_AUDIT = [
  // recently resolved (greyed in the inbox at bottom)
  { id: "esc_r1", at: "2026-05-19 17:42", ticket: 477, summary: "flaky test on signup — resolved: bumped retry tolerance in test config", outcome: "resolved" },
  { id: "esc_r2", at: "2026-05-19 11:08", ticket: 422, summary: "billing edge case — resolved: marked as known-issue, deferred to v2.5", outcome: "deferred" },
  { id: "esc_r3", at: "2026-05-18 14:30", ticket: 419, summary: "PM↔Architect scope conflict — resolved: split into 2 tickets", outcome: "resolved" },
];
