// Rich event timeline for one session — used by Session Replay
// Session s_18d4 — DevA implements #487 refactor auth middleware, gets a retry from DevB

window.SESSION_DETAIL = {
  id: "s_18d4",
  agent: "DA",
  ticket: 487,
  title: "refactor auth middleware: drop legacy cookie path",
  role: "implement",
  started: "2026-05-20 16:48:12",
  ended:   "2026-05-20 17:12:34",
  durationMin: 24,
  events: 31,
  findings: 2,
  outcome: "retry",
  retryN: 1,
  cost: { tokens: 58900, dollars: 0.62 },
  model: "claude-sonnet-4.5",
  branch: "feat/auth-mw-cookie-drop",
  commit: "a4f17b3",
  github: "https://github.com/example/api/issues/487",
  prevOnTicket: { id: "s_188a", agent: "AR", role: "spec", at: "15:14" },
  nextOnTicket: { id: "s_18e0", agent: "DA", role: "implement (retry)", at: "17:18" },
};

// Event kinds:
//   prompt        — instruction received (from another agent or system)
//   thought       — agent internal reasoning
//   tool          — tool/skill call + result
//   peer_msg      — agent-to-agent message
//   finding       — review finding (with severity & location)
//   state_change  — ticket state transition
//   retry         — retry triggered
//   escalation    — escalation raised
//   session_end   — outcome
window.SESSION_EVENTS = [
  {
    step: 1, t: "16:48:12", elapsed: "+0s",
    kind: "prompt",
    from: "AR",
    summary: "Architect → DevA · implement task",
    body: "Refactor src/middleware/auth.ts to drop the legacy cookie path. Keep behavior identical for SSO header flow. Acceptance: existing tests pass, new test covers cookie-absent path. See spec in #487. Branch: feat/auth-mw-cookie-drop.",
    bodyLength: 482,
    skills: ["follow_spec", "tdd_loop"],
  },
  {
    step: 2, t: "16:48:18", elapsed: "+6s",
    kind: "thought",
    summary: "thinking · plan implementation",
    body: "I need to: 1) read current middleware, 2) find legacy cookie references, 3) check what tests exist, 4) drop cookie path while preserving header flow, 5) add coverage for cookie-absent case. Let me read the file first.",
    duration: 5,
  },
  {
    step: 3, t: "16:49:01", elapsed: "+49s",
    kind: "tool",
    tool: "read_file",
    summary: "read_file · src/middleware/auth.ts",
    meta: "342 lines",
    body: null,
  },
  {
    step: 4, t: "16:49:08", elapsed: "+56s",
    kind: "tool",
    tool: "read_file",
    summary: "read_file · src/middleware/__tests__/auth.test.ts",
    meta: "186 lines, 23 cases",
  },
  {
    step: 5, t: "16:49:22", elapsed: "+1m 10s",
    kind: "tool",
    tool: "grep",
    summary: "grep · \"legacyAuthCookie\" in src/",
    meta: "7 matches across 4 files",
    body: "src/middleware/auth.ts:42\nsrc/middleware/auth.ts:108\nsrc/middleware/auth.ts:127\nsrc/lib/cookies.ts:18\nsrc/lib/cookies.ts:24\nsrc/server/start.ts:91\nsrc/config/auth.ts:34",
  },
  {
    step: 6, t: "16:50:34", elapsed: "+2m 22s",
    kind: "thought",
    summary: "thinking · TDD step — write failing test first",
    body: "Per TDD loop, I'll write the new test case for the cookie-absent path first, watch it fail, then implement.",
    duration: 4,
  },
  {
    step: 7, t: "16:51:18", elapsed: "+3m 06s",
    kind: "tool",
    tool: "edit_file",
    summary: "edit_file · src/middleware/__tests__/auth.test.ts",
    meta: "+38 lines",
    diff: { add: 38, del: 0 },
  },
  {
    step: 8, t: "16:51:42", elapsed: "+3m 30s",
    kind: "tool",
    tool: "run_tests",
    summary: "run_tests · vitest src/middleware",
    meta: "23 passed · 2 failed (expected)",
    body: "FAIL  src/middleware/__tests__/auth.test.ts > auth middleware > rejects request without legacy cookie or sso header\nFAIL  src/middleware/__tests__/auth.test.ts > auth middleware > falls back to header when cookie absent",
    severity: "expected",
  },
  {
    step: 9, t: "16:53:01", elapsed: "+4m 49s",
    kind: "tool",
    tool: "edit_file",
    summary: "edit_file · src/middleware/auth.ts",
    meta: "-42  +18 lines",
    diff: { add: 18, del: 42 },
  },
  {
    step: 10, t: "16:53:18", elapsed: "+5m 06s",
    kind: "tool",
    tool: "edit_file",
    summary: "edit_file · src/lib/cookies.ts",
    meta: "-12  +0 lines (remove legacyAuthCookie util)",
    diff: { add: 0, del: 12 },
  },
  {
    step: 11, t: "16:53:34", elapsed: "+5m 22s",
    kind: "tool",
    tool: "run_tests",
    summary: "run_tests · vitest src/middleware",
    meta: "25 passed",
    body: "PASS  src/middleware/__tests__/auth.test.ts  (25 tests)\nTest Files  1 passed (1)\nTests       25 passed (25)",
    severity: "ok",
  },
  {
    step: 12, t: "16:54:02", elapsed: "+5m 50s",
    kind: "tool",
    tool: "run_tests",
    summary: "run_tests · vitest (full suite)",
    meta: "1247 passed · 0 failed · 18.4s",
    severity: "ok",
  },
  {
    step: 13, t: "16:54:21", elapsed: "+6m 09s",
    kind: "tool",
    tool: "git",
    summary: "git commit · feat/auth-mw-cookie-drop",
    meta: "a4f17b3 · \"refactor(auth): drop legacy cookie path\"",
  },
  {
    step: 14, t: "16:54:33", elapsed: "+6m 21s",
    kind: "state_change",
    summary: "state → IN_REVIEW",
    body: "Ticket #487 transitioned from IN_DEVELOPMENT to IN_REVIEW. Requesting cross-review from DevB.",
  },
  {
    step: 15, t: "16:54:38", elapsed: "+6m 26s",
    kind: "peer_msg",
    direction: "out", from: "DA", to: "DB",
    summary: "DevA → DevB · cross-review request",
    body: "Cross-review request on #487. Changed files: src/middleware/auth.ts (-42 +18), src/lib/cookies.ts (-12), src/middleware/__tests__/auth.test.ts (+38). All tests green. Branch feat/auth-mw-cookie-drop @ a4f17b3.",
  },
  {
    step: 16, t: "16:56:11", elapsed: "+7m 59s",
    kind: "peer_msg",
    direction: "in", from: "DB", to: "DA",
    summary: "DevB → DevA · review acknowledged",
    body: "Acknowledged. Starting review.",
  },
  // DevB review session inlined as findings
  {
    step: 17, t: "17:02:44", elapsed: "+14m 32s",
    kind: "finding",
    from: "DB",
    severity: "medium",
    location: "src/middleware/auth.ts:127",
    summary: "missing test for csrf header propagation",
    body: "The new code drops the legacy cookie path but doesn't test that csrf header still ships through when only the bearer token is present. Add coverage for: (1) header present, no cookie → csrf attached, (2) both present → header wins.",
  },
  {
    step: 18, t: "17:03:09", elapsed: "+14m 57s",
    kind: "finding",
    from: "DB",
    severity: "low",
    location: "src/middleware/auth.ts:42",
    summary: "leftover unused import",
    body: "import { legacyAuthCookie } from '../lib/cookies' — this is now dead code. Remove.",
  },
  {
    step: 19, t: "17:03:38", elapsed: "+15m 26s",
    kind: "peer_msg",
    direction: "in", from: "DB", to: "DA",
    summary: "DevB → DevA · changes requested",
    body: "2 findings — see inline. Please address and request re-review.",
  },
  {
    step: 20, t: "17:03:52", elapsed: "+15m 40s",
    kind: "thought",
    summary: "thinking · evaluate findings",
    body: "Both findings are valid. Finding #1 (csrf coverage) is genuinely missing — I should have written that test. Finding #2 is a trivial leftover. Let me address both before requesting re-review.",
    duration: 6,
  },
  {
    step: 21, t: "17:05:14", elapsed: "+17m 02s",
    kind: "tool",
    tool: "edit_file",
    summary: "edit_file · src/middleware/auth.ts",
    meta: "-1 (unused import)",
    diff: { add: 0, del: 1 },
  },
  {
    step: 22, t: "17:07:33", elapsed: "+19m 21s",
    kind: "tool",
    tool: "edit_file",
    summary: "edit_file · src/middleware/__tests__/auth.test.ts",
    meta: "+22 lines (2 new csrf cases)",
    diff: { add: 22, del: 0 },
  },
  {
    step: 23, t: "17:07:51", elapsed: "+19m 39s",
    kind: "tool",
    tool: "run_tests",
    summary: "run_tests · vitest src/middleware",
    meta: "27 passed",
    severity: "ok",
  },
  {
    step: 24, t: "17:08:14", elapsed: "+20m 02s",
    kind: "tool",
    tool: "git",
    summary: "git commit · fixup",
    meta: "b1e9d22 · \"fixup: address review findings\"",
  },
  {
    step: 25, t: "17:08:23", elapsed: "+20m 11s",
    kind: "peer_msg",
    direction: "out", from: "DA", to: "DB",
    summary: "DevA → DevB · re-review request",
    body: "Addressed both findings. Added 2 csrf test cases (header-only and both-present). Removed unused import. Ready for re-review @ b1e9d22.",
  },
  {
    step: 26, t: "17:11:48", elapsed: "+23m 36s",
    kind: "retry",
    summary: "retry recorded · 1/3 (review loop)",
    body: "First retry on cross-review loop. Reason: review findings addressed. Counter increments after re-review completes.",
  },
  {
    step: 27, t: "17:12:34", elapsed: "+24m 22s",
    kind: "session_end",
    summary: "session ended · outcome: retry 1/3",
    body: "Handed off to next DevA session for re-review iteration. Pending DevB acknowledgement.",
    outcome: "retry",
  },
];

window.SESSION_OUTLINE = [
  { step: 1, label: "prompt received", icon: "▸" },
  { step: 3, label: "context reading (3 reads)", icon: "⚒" },
  { step: 7, label: "TDD: failing test", icon: "⚒" },
  { step: 9, label: "implementation", icon: "⚒" },
  { step: 11, label: "tests green", icon: "✓" },
  { step: 14, label: "→ IN_REVIEW", icon: "↦" },
  { step: 17, label: "2 findings from DevB", icon: "◇" },
  { step: 21, label: "address findings", icon: "⚒" },
  { step: 26, label: "retry 1/3 recorded", icon: "↻" },
  { step: 27, label: "session end", icon: "◐" },
];
