// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Tickets;
using Microsoft.Data.Sqlite;

namespace AgentDashboard.TicketTracking.Infrastructure.UnitTests.Tickets;

// Test list for schema bootstrap idempotency (regression guard for the
// multi-instance / WAL-visibility "table tickets already exists" defect):
// ========================================================================
// [x] Constructing_TwiceAgainstSameFile_DoesNotThrow
// [x] Constructing_ConcurrentlyAgainstSameFreshFile_DoesNotThrow   <- reproduces the defect
// [x] Constructing_TwiceAgainstSameFile_LeavesSchemaUsableForBothInstances
// ========================================================================

public sealed class SqliteTicketWriteRepositorySchemaBootstrapTests : IDisposable
{
    private readonly string _testDbPath;

    public SqliteTicketWriteRepositorySchemaBootstrapTests()
        => _testDbPath = Path.Combine(
            Path.GetTempPath(),
            "schema-bootstrap-" + Guid.NewGuid().ToString("N") + ".db");

    public void Dispose()
    {
        SqliteConnection.ClearAllPools();
        TryDelete(_testDbPath);
        TryDelete(_testDbPath + "-wal");
        TryDelete(_testDbPath + "-shm");
    }

    private static void TryDelete(string path)
    {
        if (File.Exists(path))
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void Constructing_TwiceAgainstSameFile_DoesNotThrow()
    {
        var connectionString = "Data Source=" + _testDbPath;

        var construct = () =>
        {
            _ = new SqliteTicketWriteRepository(connectionString);
            _ = new SqliteTicketWriteRepository(connectionString);
        };

        construct.Should().NotThrow();
    }

    [Fact]
    public void Constructing_ConcurrentlyAgainstSameFreshFile_DoesNotThrow()
    {
        var connectionString = "Data Source=" + _testDbPath;
        const int concurrentConstructions = 8;

        var construct = () =>
        {
            var barrier = new Barrier(concurrentConstructions);
            var tasks = new Task[concurrentConstructions];
            for (var i = 0; i < concurrentConstructions; i++)
            {
                tasks[i] = Task.Run(() =>
                {
                    barrier.SignalAndWait();
                    _ = new SqliteTicketWriteRepository(connectionString);
                });
            }

            Task.WaitAll(tasks);
        };

        construct.Should().NotThrow();
    }

    [Fact]
    public async Task Constructing_TwiceAgainstSameFile_LeavesSchemaUsableForBothInstances()
    {
        var connectionString = "Data Source=" + _testDbPath;

        var first = new SqliteTicketWriteRepository(connectionString);
        var second = new SqliteTicketWriteRepository(connectionString);

        await first.SaveAsync(CreateTestTicket(1, "first"), CancellationToken.None);
        await second.SaveAsync(CreateTestTicket(2, "second"), CancellationToken.None);

        await using var connection = new SqliteConnection(connectionString);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = new SqliteCommand("SELECT COUNT(*) FROM tickets", connection);
        var count = (long)await command.ExecuteScalarAsync(CancellationToken.None);

        count.Should().Be(2);
    }

    private static Ticket CreateTestTicket(int issueNumber, string title)
        => new(
            new GitHubRepository("AskmethatFR/agent-dashboard"),
            new GitHubIssueNumber(issueNumber),
            new TicketTitle(title),
            TicketStatusValue.Created,
            new AgentId("pm"),
            new Retry(0),
            new GitHubUrl("https://github.com/AskmethatFR/agent-dashboard/issues/" + issueNumber),
            DateTimeOffset.UtcNow,
            DateTimeOffset.UtcNow,
            null);
}
