// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

using System;
using System.IO;
using System.Threading.Tasks;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Tickets;
using Microsoft.Data.Sqlite;

namespace AgentDashboard.TicketTracking.Infrastructure.UnitTests.Tickets;

public sealed class SqliteTicketWriteRepositoryTests : IDisposable
{
    private readonly string _testDbPath;
    private readonly SqliteTicketWriteRepository _repository;

    public SqliteTicketWriteRepositoryTests()
    {
        _testDbPath = Path.GetTempFileName();
        _repository = new SqliteTicketWriteRepository(
            "Data Source=" + _testDbPath);
    }

    public void Dispose() => File.Delete(_testDbPath);

    // Test List for SqliteTicketWriteRepository:
    // ========================================================================
    //
    // HAPPY PATH:
    // [x] SaveAsync_Should_InsertNewTicket
    // [x] SaveAsync_Should_UpdateExistingTicket_When_SameCompositeKey
    // [x] SaveAsync_Should_NotCreateDuplicateRows
    //
    // ========================================================================

    [Fact]
    public async Task SaveAsync_Should_InsertNewTicket()
    {
        // Arrange
        var ticket = CreateTestTicket(1, "Test Ticket");

        // Act
        await _repository.SaveAsync(ticket, CancellationToken.None);

        // Assert
        // Verify the ticket was inserted by reading from the database
        await using var connection = new SqliteConnection("Data Source=" + _testDbPath);
        await connection.OpenAsync(CancellationToken.None);

        await using var command = new SqliteCommand("SELECT COUNT(*) FROM tickets", connection);
        var count = (long)await command.ExecuteScalarAsync(CancellationToken.None);

        count.Should().Be(1);
    }

    [Fact]
    public async Task SaveAsync_Should_UpdateExistingTicket_When_SameCompositeKey()
    {
        // Arrange
        var ticket1 = CreateTestTicket(1, "Original Title");
        var ticket2 = CreateTestTicket(1, "Updated Title");

        // Act - save first ticket, then save second with same key
        await _repository.SaveAsync(ticket1, CancellationToken.None);
        await _repository.SaveAsync(ticket2, CancellationToken.None);

        // Assert
        await using var connection = new SqliteConnection("Data Source=" + _testDbPath);
        await connection.OpenAsync(CancellationToken.None);

        await using var command = new SqliteCommand("SELECT title FROM tickets WHERE github_issue_number = 1", connection);
        var title = (string)await command.ExecuteScalarAsync(CancellationToken.None);

        title.Should().Be("Updated Title");
    }

    [Fact]
    public async Task SaveAsync_Should_NotCreateDuplicateRows()
    {
        // Arrange
        var ticket = CreateTestTicket(1, "Test Ticket");

        // Act - save the same ticket twice
        await _repository.SaveAsync(ticket, CancellationToken.None);
        await _repository.SaveAsync(ticket, CancellationToken.None);

        // Assert
        await using var connection = new SqliteConnection("Data Source=" + _testDbPath);
        await connection.OpenAsync(CancellationToken.None);

        await using var command = new SqliteCommand("SELECT COUNT(*) FROM tickets", connection);
        var count = (long)await command.ExecuteScalarAsync(CancellationToken.None);

        count.Should().Be(1);
    }

    // Helper method to create test tickets
    private static Ticket CreateTestTicket(int issueNumber, string title)
    {
        return new Ticket(
            new RepositorySource("AskmethatFR/agent-dashboard"),
            new GitHubIssueNumber(issueNumber),
            new TicketTitle(title),
            TicketStatusValue.Created,
            new AgentId("pm"),
            new Retry(0),
            new GitHubUrl("https://github.com/AskmethatFR/agent-dashboard/issues/" + issueNumber),
            DateTimeOffset.UtcNow,
            DateTimeOffset.UtcNow,
            null);
    }
}
