// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

using System;
using System.IO;
using System.Threading.Tasks;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Tickets;
using Microsoft.Data.Sqlite;

namespace AgentDashboard.TicketTracking.Infrastructure.UnitTests.Tickets;

// Test List for on-disk timestamp byte-compatibility (T2):
// ========================================================================
//  [x] created_at_utc is persisted verbatim as TimestampUtc.ToString("o")
//      — pins that the EF rewrite preserves the exact on-disk string format
//        the old raw-ADO repository wrote (DateTimeOffset round-trip "o").
// ========================================================================

public sealed class SqliteTicketWriteRepositoryTimestampFormatTests : IDisposable
{
    private readonly string _testDbPath;
    private readonly SqliteTicketWriteRepository _repository;

    public SqliteTicketWriteRepositoryTimestampFormatTests()
    {
        _testDbPath = Path.GetTempFileName();
        _repository = new SqliteTicketWriteRepository("Data Source=" + _testDbPath);
    }

    public void Dispose() => File.Delete(_testDbPath);

    [Fact]
    public async Task SaveAsync_PersistsTimestampsInRoundTripFormat_OnDisk()
    {
        var created = new DateTimeOffset(2026, 5, 22, 9, 0, 0, TimeSpan.Zero);
        var ticket = new Ticket(
            new GitHubRepository("AskmethatFR/agent-dashboard"),
            new GitHubIssueNumber(1),
            new TicketTitle("Timestamp byte-compat"),
            TicketStatusValue.Created,
            new AgentId("pm"),
            new Retry(0),
            new GitHubUrl("https://github.com/AskmethatFR/agent-dashboard/issues/1"),
            created,
            created.AddHours(1),
            created.AddHours(2));

        await _repository.SaveAsync(ticket, CancellationToken.None);

        await using var connection = new SqliteConnection("Data Source=" + _testDbPath);
        await connection.OpenAsync(CancellationToken.None);
        await using var command = new SqliteCommand(
            "SELECT created_at_utc, updated_at_utc, closed_at_utc FROM tickets WHERE github_issue_number = 1",
            connection);
        await using var reader = await command.ExecuteReaderAsync(CancellationToken.None);
        (await reader.ReadAsync(CancellationToken.None)).Should().BeTrue();

        reader.GetString(0).Should().Be(ticket.CreatedAtUtc.ToString());
        reader.GetString(1).Should().Be(ticket.UpdatedAtUtc.ToString());
        reader.GetString(2).Should().Be(ticket.ClosedAtUtc!.ToString());
    }
}
