// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Boards;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Boards;
using AgentDashboard.Web.Store;
using Blazor.Redux.Interfaces;
using Microsoft.Extensions.Logging;
using NSubstitute;
using Xunit;

namespace AgentDashboard.Web.Tests.Store;

// Test List for BoardCacheMonitor:
// ========================================================================
//
// CONSTRUCTOR & DISPOSAL:
// [✓] Constructor_WithNullCache_ThrowsArgumentNullException
// [✓] Constructor_WithNullDispatcher_ThrowsArgumentNullException
// [✓] Constructor_WithNullLogger_ThrowsArgumentNullException
//
// EVENT HANDLING:
// [✓] HandleCacheUpdated_WhenDispatchFails_LogsError
// [✓] HandleCacheUpdated_DispatchesLoadBoardAction
// [✓] Dispose_UnsubscribesFromCacheEvent
//
// ========================================================================

public sealed class BoardCacheMonitorTests
{
    private readonly ILogger<BoardCacheMonitor> _logger = Substitute.For<ILogger<BoardCacheMonitor>>();

    // -----------------------------------------------------------------------------
    // Constructor & Disposal
    // -----------------------------------------------------------------------------

    [Fact]
    public void Constructor_WithNullCache_ThrowsArgumentNullException()
    {
        // Arrange
        var dispatcher = Substitute.For<IAsyncDispatcher>();

        // Act & Assert
        Assert.Throws<ArgumentNullException>(() =>
            new BoardCacheMonitor(null!, dispatcher, _logger));
    }

    [Fact]
    public void Constructor_WithNullDispatcher_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();

        // Act & Assert
        Assert.Throws<ArgumentNullException>(() =>
            new BoardCacheMonitor(cache, null!, _logger));
    }

    [Fact]
    public void Constructor_WithNullLogger_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var dispatcher = Substitute.For<IAsyncDispatcher>();

        // Act & Assert
        Assert.Throws<ArgumentNullException>(() =>
            new BoardCacheMonitor(cache, dispatcher, null!));
    }

    // -----------------------------------------------------------------------------
    // Event Handling
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task HandleCacheUpdated_DispatchesLoadBoardAction()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var dispatcher = Substitute.For<IAsyncDispatcher>();

        // Create the monitor - it will subscribe to cache.OnUpdated
        using var monitor = new BoardCacheMonitor(cache, dispatcher, _logger);

        // Act - trigger the cache update which should trigger the event
        cache.Update(BuildTestSnapshot(), DateTimeOffset.UtcNow);

        // Assert - dispatcher should have been called to dispatch LoadBoardAction
        // Note: Since HandleCacheUpdated is async void, we need to wait a bit
        await Task.Delay(100);

        await dispatcher.Received(1).DispatchAsync<BoardSlice, LoadBoardAction>(Arg.Any<LoadBoardAction>());
    }

    [Fact]
    public async Task Dispose_UnsubscribesFromCacheEvent()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var dispatcher = Substitute.For<IAsyncDispatcher>();

        // Create the monitor
        var monitor = new BoardCacheMonitor(cache, dispatcher, _logger);

        // Act - dispose the monitor
        monitor.Dispose();

        // Assert - after disposal, cache updates should not trigger dispatch
        cache.Update(BuildTestSnapshot(), DateTimeOffset.UtcNow);

        // Wait a bit and verify no dispatch occurred
        await Task.Delay(100);

        await dispatcher.DidNotReceive().DispatchAsync<BoardSlice, LoadBoardAction>(Arg.Any<LoadBoardAction>());
    }


    [Fact]
    public async Task HandleCacheUpdated_WhenDispatchFails_LogsError()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var dispatcher = Substitute.For<IAsyncDispatcher>();
        var logger = Substitute.For<ILogger<BoardCacheMonitor>>();
        logger.IsEnabled(LogLevel.Error).Returns(true);

        dispatcher
            .DispatchAsync<BoardSlice, LoadBoardAction>(Arg.Any<LoadBoardAction>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromException(new Exception("Dispatch failed")));

        // Act
        using var monitor = new BoardCacheMonitor(cache, dispatcher, logger);
        cache.Update(BuildTestSnapshot(), DateTimeOffset.UtcNow);

        // Wait for async void to complete - increased delay
        await Task.Delay(500);

        // Assert - logger should have been called with error level
        logger.Received(1).Log(
            LogLevel.Error,
            Arg.Any<EventId>(),
            Arg.Any<Arg.AnyType>(),
            Arg.Any<Exception>(),
            Arg.Any<Func<Arg.AnyType, Exception, string>>());
    }
    // -----------------------------------------------------------------------------
    // Helper Methods
    // -----------------------------------------------------------------------------

    private static BoardSnapshot BuildTestSnapshot(int ticketId = 1)
    {
        var column = new BoardColumn(new BoardColumnId("CREATED"), new BoardColumnLabel("Created"));
        var agent = new Agent(new AgentId("DA"), new AgentName("Developer A"), new AgentGlyph("DA"), new AgentRole("developer"));
        var ticket = TicketSnapshot.Open(
            new TicketId(ticketId),
            column.Id,
            new TicketTitle("Test TicketSnapshot"),
            agent.Id,
            new Retry(0),
            new Age(TimeSpan.Zero),
            thinking: false,
            freshness: TicketFreshness.Neutral);

        return new BoardSnapshot(
            new[] { column },
            new[] { ticket },
            new[] { agent });
    }
}
