// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using AgentDashboard.TicketTracking.Application.Ports;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Boards;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Boards;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace AgentDashboard.TicketTracking.Infrastructure.UnitTests.Boards;

public sealed class CachedBoardReaderTests
{
    private static readonly DateTimeOffset FixedAsOf = new(2026, 05, 27, 12, 0, 0, TimeSpan.Zero);

    [Fact]
    public async Task GetCurrentAsync_ReturnsCachedSnapshot_WhenCachePopulated()
    {
        // Arrange
        var cache = new BoardSnapshotCache();
        var expectedSnapshot = BuildTestSnapshot();
        cache.Update(expectedSnapshot, FixedAsOf);
        
        var reader = new CachedBoardReader(cache, NullLogger<CachedBoardReader>.Instance);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().BeSameAs(expectedSnapshot);
    }

    [Fact]
    public async Task GetCurrentAsync_ThrowsInvalidOperationException_WhenCacheEmpty()
    {
        // Arrange
        var cache = new BoardSnapshotCache();
        var reader = new CachedBoardReader(cache, NullLogger<CachedBoardReader>.Instance);

        // Act
        var act = () => reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>(
            "because the cache is empty and cannot return a board snapshot");
    }

    [Fact]
    public void Constructor_WithNullCache_ThrowsArgumentNullException()
    {
        // Arrange & Act
        var act = () => new CachedBoardReader(null!, NullLogger<CachedBoardReader>.Instance);

        // Assert
        act.Should().Throw<ArgumentNullException>(
            "because the cache parameter cannot be null");
    }

    [Fact]
    public async Task GetCurrentAsync_WithCancellationRequested_ThrowsOperationCanceledException()
    {
        // Arrange
        var cache = new BoardSnapshotCache();
        cache.Update(BuildTestSnapshot(), FixedAsOf);
        var reader = new CachedBoardReader(cache, NullLogger<CachedBoardReader>.Instance);
        
        using var cts = new CancellationTokenSource();
        cts.Cancel();

        // Act
        var act = () => reader.GetCurrentAsync(cts.Token);

        // Assert
        await act.Should().ThrowAsync<OperationCanceledException>();
    }

    [Fact]
    public async Task GetCurrentAsync_WithNullLogger_WorksCorrectly()
    {
        // Arrange
        var cache = new BoardSnapshotCache();
        cache.Update(BuildTestSnapshot(), FixedAsOf);
        var reader = new CachedBoardReader(cache, null);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
    }

    // Helper method to create a BoardSnapshot for testing
    private static BoardSnapshot BuildTestSnapshot(int ticketId = 1)
    {
        var column = new BoardColumn(new BoardColumnId("CREATED"), new BoardColumnLabel("Created"));
        var agent = new Agent(new AgentId("DA"), new AgentName("Developer A"), new AgentGlyph("DA"), new AgentRole("developer"));
        var ticket = TicketSnapshot.Open(
            new TicketId(ticketId),
            column.Id,
            new TicketTitle("Test TicketSnapshot"),
            agent.Id,
            new Retry(0),
            new Age(TimeSpan.Zero),
            thinking: false,
            freshness: TicketFreshness.Neutral);

        return new BoardSnapshot(
            new[] { column },
            new[] { ticket },
            new[] { agent });
    }
}
