// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

#nullable disable

using System;
using System.Threading.Tasks;
using AgentDashboard.TicketTracking.Application.GitHub;
using AgentDashboard.TicketTracking.Application.Ports;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Boards;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Boards;
using AgentDashboard.TicketTracking.Infrastructure.GitHub;
using AgentDashboard.TicketTracking.Infrastructure.UnitTests.GitHub.Fakes;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace AgentDashboard.TicketTracking.Infrastructure.UnitTests.Boards;

// Test List for GitHubBoardReader:
// ========================================================================
//
// CACHE HIT SCENARIOS:
// [✓] GetCurrentAsync_WhenCacheHasRecentData_ReturnsCachedSnapshot
//
// CACHE MISS SCENARIOS:
// [✓] GetCurrentAsync_WhenCacheIsEmpty_PollGitHubAndReturnsSnapshot
// [✓] GetCurrentAsync_WhenCacheIsStale_PollGitHubAndUpdatesCache
//
// ERROR HANDLING SCENARIOS:
// [✓] GetCurrentAsync_WhenPollingFailsAndCacheHasData_ReturnsCachedSnapshot
// [✓] GetCurrentAsync_WhenPollingFailsAndCacheIsEmpty_ThrowsException
//
// EDGE CASES:
// [✓] GetCurrentAsync_WhenPollIntervalIsZero_AlwaysPoll
// [✓] GetCurrentAsync_WhenCacheLastUpdatedIsMinValue_PollGitHub
//
// ========================================================================

public sealed class GitHubBoardReaderTests
{
    private static readonly DateTimeOffset FixedNow = new(2026, 05, 27, 12, 0, 0, TimeSpan.Zero);
    private static readonly TimeSpan DefaultPollInterval = TimeSpan.FromMinutes(10);

    private static readonly ILogger<GitHubBoardReader> NullLogger = NullLogger<GitHubBoardReader>.Instance;

    // -----------------------------------------------------------------------------
    // Cache Hit Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenCacheHasRecentData_ReturnsCachedSnapshot()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var cachedSnapshot = BuildTestSnapshot(ticketId: 1);
        
        cache.Update(cachedSnapshot, FixedNow);
        
        // Use a very large poll interval so cache is always fresh
        var largeIntervalOptions = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = TimeSpan.FromDays(365) // 1 year - cache will always be fresh
        };
        
        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var timeProvider = new ManualTimeProvider(FixedNow);
        
        var reader = new GitHubBoardReader(cache, client, largeIntervalOptions, timeProvider, NullLogger);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().BeSameAs(cachedSnapshot);
        client.CallCount.Should().Be(0); // Client should not be called
    }

    // -----------------------------------------------------------------------------
    // Cache Miss Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenCacheIsEmpty_PollGitHubAndReturnsSnapshot()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // Cache is empty (default state)
        
        var records = new List<GitHubIssueRecord>
        {
            new(1, "Test Issue", new List<string> { "status:created", "agent:pm" }, FixedNow.AddHours(-1))
        };
        var client = new FakeGitHubIssuesClient(records);
        var timeProvider = new ManualTimeProvider(FixedNow);
        
        var options = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = DefaultPollInterval
        };
        
        var reader = new GitHubBoardReader(cache, client, options, timeProvider, NullLogger);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Tickets.Should().HaveCount(1);
        client.CallCount.Should().Be(1); // Client should be called once
        cache.GetLatest().Should().BeSameAs(result); // Cache should be updated
    }

    [Fact]
    public async Task GetCurrentAsync_WhenCacheIsStale_PollGitHubAndUpdatesCache()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var oldSnapshot = BuildTestSnapshot(ticketId: 1);
        cache.Update(oldSnapshot, FixedNow);

        var shortIntervalOptions = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = TimeSpan.FromMilliseconds(100)
        };

        var timeAfterCache = FixedNow.AddMilliseconds(150);
        var timeProvider = new ManualTimeProvider(timeAfterCache);
        
        var records = new List<GitHubIssueRecord>
        {
            new(2, "New Issue", new List<string> { "status:created", "agent:pm" }, FixedNow)
        };
        var client = new FakeGitHubIssuesClient(records);
        
        var reader = new GitHubBoardReader(cache, client, shortIntervalOptions, timeProvider, NullLogger);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Tickets.Should().HaveCount(1);
        result.Tickets[0].Id.Value.Should().Be(2); // New ticket
        client.CallCount.Should().Be(1); // Client should be called
        cache.GetLatest().Should().BeSameAs(result); // Cache should be updated
    }

    // -----------------------------------------------------------------------------
    // Error Handling Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenPollingFailsAndCacheHasData_ReturnsCachedSnapshot()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var cachedSnapshot = BuildTestSnapshot(ticketId: 1);
        cache.Update(cachedSnapshot, FixedNow);

        var largeIntervalOptions = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = TimeSpan.FromDays(365)
        };
        
        var failingClient = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>(), shouldFail: true);
        var timeProvider = new ManualTimeProvider(FixedNow);
        
        var reader = new GitHubBoardReader(cache, failingClient, largeIntervalOptions, timeProvider, NullLogger);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().BeSameAs(cachedSnapshot); // Should return cached data
        failingClient.CallCount.Should().Be(0); // Client should not be called when cache is fresh
    }

    [Fact]
    public async Task GetCurrentAsync_WhenPollingFailsAndCacheIsEmpty_ThrowsException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // Cache is empty
        
        var failingClient = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>(), shouldFail: true);
        var timeProvider = new ManualTimeProvider(FixedNow);
        
        var options = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = DefaultPollInterval
        };
        
        var reader = new GitHubBoardReader(cache, failingClient, options, timeProvider, NullLogger);

        // Act
        Func<Task> act = async () => await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>(); // Should throw
    }

    // -----------------------------------------------------------------------------
    // Edge Cases
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenPollIntervalIsZero_AlwaysPoll()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var cachedSnapshot = BuildTestSnapshot(ticketId: 1);
        cache.Update(cachedSnapshot, FixedNow);

        var zeroIntervalOptions = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = TimeSpan.Zero
        };
        
        var records = new List<GitHubIssueRecord>
        {
            new(2, "New Issue", new List<string> { "status:created", "agent:pm" }, FixedNow)
        };
        var client = new FakeGitHubIssuesClient(records);
        var timeProvider = new ManualTimeProvider(FixedNow);
        
        var reader = new GitHubBoardReader(cache, client, zeroIntervalOptions, timeProvider, NullLogger);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        // With zero interval, cache is always stale, so it should poll
        client.CallCount.Should().Be(1);
        result.Tickets.Should().HaveCount(1);
        result.Tickets[0].Id.Value.Should().Be(2);
    }

    [Fact]
    public async Task GetCurrentAsync_WhenCacheIsStaleDueToMinValueLastUpdated_PollGitHub()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // LastUpdated is MinValue by default, so cache is stale
        
        var records = new List<GitHubIssueRecord>
        {
            new(1, "Test Issue", new List<string> { "status:created", "agent:pm" }, FixedNow)
        };
        var client = new FakeGitHubIssuesClient(records);
        var timeProvider = new ManualTimeProvider(FixedNow);
        
        var options = new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = DefaultPollInterval
        };
        
        var reader = new GitHubBoardReader(cache, client, options, timeProvider, NullLogger);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        client.CallCount.Should().Be(1); // Should poll because cache is stale
        result.Should().NotBeNull();
    }

    // -----------------------------------------------------------------------------
    // Helper Methods
    // -----------------------------------------------------------------------------

    private static BoardSnapshot BuildTestSnapshot(int ticketId = 1)
    {
        var column = new BoardColumn(new BoardColumnId("CREATED"), new BoardColumnLabel("Created"));
        var agent = new Agent(new AgentId("pm"), new AgentName("Project Manager"), new AgentGlyph("PM"), new AgentRole("project-manager"));
        var ticket = Ticket.Open(
            new TicketId(ticketId),
            column.Id,
            new TicketTitle("Test Ticket"),
            agent.Id,
            new Retry(0),
            new Age(TimeSpan.Zero),
            thinking: false,
            freshness: TicketFreshness.Neutral);

        return new BoardSnapshot(
            new[] { column },
            new[] { ticket },
            new[] { agent });
    }

    // Manual time provider that allows us to control the current time
    private sealed class ManualTimeProvider : TimeProvider
    {
        private readonly DateTimeOffset _fixedTime;

        public ManualTimeProvider(DateTimeOffset fixedTime)
        {
            _fixedTime = fixedTime;
        }

        public override DateTimeOffset GetUtcNow() => _fixedTime;
    }
}
