// <auto-generated>IDE0005 disable for test files - global usings handle FluentAssertions/Xunit</auto-generated>
#pragma warning disable IDE0005 // Using directive is unnecessary

#nullable disable

using System;
using System.Threading.Tasks;
using AgentDashboard.TicketTracking.Application.GitHub;
using AgentDashboard.TicketTracking.Application.Ports;
using AgentDashboard.TicketTracking.Domain.Agents;
using AgentDashboard.TicketTracking.Domain.Boards;
using AgentDashboard.TicketTracking.Domain.Tickets;
using AgentDashboard.TicketTracking.Infrastructure.Boards;
using AgentDashboard.TicketTracking.Infrastructure.GitHub;
using AgentDashboard.TicketTracking.Infrastructure.UnitTests.GitHub.Fakes;
using AgentDashboard.TicketTracking.Infrastructure.UnitTests.Boards.Fakes;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

// Test List for GitHubBoardReader:
// ========================================================================
//
// CACHE HIT SCENARIOS:
// [✓] GetCurrentAsync_WhenCacheHasRecentData_ReturnsCachedSnapshot
//
// CACHE MISS SCENARIOS:
// [✓] GetCurrentAsync_WhenCacheIsEmpty_PollGitHubAndReturnsSnapshot
// [✓] GetCurrentAsync_WhenCacheIsStale_PollGitHubAndUpdatesCache
//
// ERROR HANDLING SCENARIOS:
// [✓] GetCurrentAsync_WhenPollingFailsAndCacheHasData_ReturnsCachedSnapshot
// [✓] GetCurrentAsync_WhenPollingFailsAndCacheIsEmpty_ThrowsException
//
// EDGE CASES:
// [✓] GetCurrentAsync_WhenPollIntervalIsZero_AlwaysPoll
// [✓] GetCurrentAsync_WhenCacheLastUpdatedIsMinValue_PollGitHub
// [✓] GetCurrentAsync_WhenSnapshotUpdaterFailsToUpdateCache_ThrowsInvalidOperationException
//
// CONSTRUCTOR NULL CHECKS:
// [✓] Constructor_WithNullCache_ThrowsArgumentNullException
// [✓] Constructor_WithNullClient_ThrowsArgumentNullException
// [✓] Constructor_WithNullSnapshotUpdater_ThrowsArgumentNullException
// [✓] Constructor_WithNullOptions_ThrowsArgumentNullException
// [✓] Constructor_WithNullTimeProvider_ThrowsArgumentNullException
// [✓] Constructor_WithNullLogger_ThrowsArgumentNullException
//
// ========================================================================
// [✓] GetCurrentAsync_WhenCacheIsEmpty_PollGitHubAndReturnsSnapshot
// [✓] GetCurrentAsync_WhenCacheIsStale_PollGitHubAndUpdatesCache
//
// ERROR HANDLING SCENARIOS:
// [✓] GetCurrentAsync_WhenPollingFailsAndCacheHasData_ReturnsCachedSnapshot
// [✓] GetCurrentAsync_WhenPollingFailsAndCacheIsEmpty_ThrowsException
//
// EDGE CASES:
// [✓] GetCurrentAsync_WhenPollIntervalIsZero_AlwaysPoll
// [✓] GetCurrentAsync_WhenCacheLastUpdatedIsMinValue_PollGitHub
// [✓] GetCurrentAsync_WhenSnapshotUpdaterFailsToUpdateCache_ThrowsInvalidOperationException
//
// ========================================================================

public sealed class GitHubBoardReaderTests
{
    private static readonly DateTimeOffset FixedNow = new(2026, 05, 27, 12, 0, 0, TimeSpan.Zero);
    private static readonly TimeSpan DefaultPollInterval = TimeSpan.FromMinutes(10);

    private static readonly ILogger<GitHubBoardReader> NullLogger = NullLogger<GitHubBoardReader>.Instance;

    // -----------------------------------------------------------------------------
    // Cache Hit Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenCacheHasRecentData_ReturnsCachedSnapshot()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var cachedSnapshot = BuildTestSnapshot(ticketId: 1);
        
        cache.Update(cachedSnapshot, FixedNow);

        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var reader = BuildReader(cache, client, BuildOptions(pollInterval: TimeSpan.FromDays(365)), FixedNow);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().BeSameAs(cachedSnapshot);
        client.CallCount.Should().Be(0); // Client should not be called
    }

    // -----------------------------------------------------------------------------
    // Cache Miss Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenCacheIsEmpty_PollGitHubAndReturnsSnapshot()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // Cache is empty (default state)
        
        var records = new List<GitHubIssueRecord>
        {
            new(1, "Test Issue", new List<string> { "status:created", "agent:pm" }, FixedNow.AddHours(-1),
                "https://github.com/AskmethatFR/agent-dashboard/issues/1", FixedNow.AddHours(-1), null)
        };
        var client = new FakeGitHubIssuesClient(records);
        var reader = BuildReader(cache, client, BuildOptions(), FixedNow);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Tickets.Should().HaveCount(1);
        client.CallCount.Should().Be(1); // Client should be called once
        cache.GetLatest().Should().BeSameAs(result); // Cache should be updated
    }

    [Fact]
    public async Task GetCurrentAsync_WhenCacheIsStale_PollGitHubAndUpdatesCache()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var oldSnapshot = BuildTestSnapshot(ticketId: 1);
        cache.Update(oldSnapshot, FixedNow);

        var timeAfterCache = FixedNow.AddMilliseconds(150);

        var records = new List<GitHubIssueRecord>
        {
            new(2, "New Issue", new List<string> { "status:created", "agent:pm" }, FixedNow,
                "https://github.com/AskmethatFR/agent-dashboard/issues/2", FixedNow, null)
        };
        var client = new FakeGitHubIssuesClient(records);
        var reader = BuildReader(cache, client, BuildOptions(pollInterval: TimeSpan.FromMilliseconds(100)), timeAfterCache);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.Tickets.Should().HaveCount(1);
        result.Tickets[0].Id.Value.Should().Be(2); // New ticket
        client.CallCount.Should().Be(1); // Client should be called
        cache.GetLatest().Should().BeSameAs(result); // Cache should be updated
    }

    // -----------------------------------------------------------------------------
    // Error Handling Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenPollingFailsAndCacheHasData_ReturnsCachedSnapshot()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var cachedSnapshot = BuildTestSnapshot(ticketId: 1);
        cache.Update(cachedSnapshot, FixedNow);

        var failingClient = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>(), shouldFail: true);
        var reader = BuildReader(cache, failingClient, BuildOptions(pollInterval: TimeSpan.FromDays(365)), FixedNow);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        result.Should().BeSameAs(cachedSnapshot); // Should return cached data
        failingClient.CallCount.Should().Be(0); // Client should not be called when cache is fresh
    }

    [Fact]
    public async Task GetCurrentAsync_WhenPollingFailsAndCacheIsEmpty_ThrowsException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // Cache is empty
        
        var failingClient = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>(), shouldFail: true);
        var reader = BuildReader(cache, failingClient, BuildOptions(), FixedNow);

        // Act
        Func<Task> act = async () => await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>(); // Should throw
    }

    // -----------------------------------------------------------------------------
    // Edge Cases
    // -----------------------------------------------------------------------------

    [Fact]
    public async Task GetCurrentAsync_WhenPollIntervalIsZero_AlwaysPoll()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var cachedSnapshot = BuildTestSnapshot(ticketId: 1);
        cache.Update(cachedSnapshot, FixedNow);

        var records = new List<GitHubIssueRecord>
        {
            new(2, "New Issue", new List<string> { "status:created", "agent:pm" }, FixedNow,
                "https://github.com/AskmethatFR/agent-dashboard/issues/2", FixedNow, null)
        };
        var client = new FakeGitHubIssuesClient(records);
        var reader = BuildReader(cache, client, BuildOptions(pollInterval: TimeSpan.Zero), FixedNow);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        // With zero interval, cache is always stale, so it should poll
        client.CallCount.Should().Be(1);
        result.Tickets.Should().HaveCount(1);
        result.Tickets[0].Id.Value.Should().Be(2);
    }

    [Fact]
    public async Task GetCurrentAsync_WhenCacheIsStaleDueToMinValueLastUpdated_PollGitHub()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // LastUpdated is MinValue by default, so cache is stale
        
        var records = new List<GitHubIssueRecord>
        {
            new(1, "Test Issue", new List<string> { "status:created", "agent:pm" }, FixedNow,
                "https://github.com/AskmethatFR/agent-dashboard/issues/1", FixedNow, null)
        };
        var client = new FakeGitHubIssuesClient(records);
        var reader = BuildReader(cache, client, BuildOptions(), FixedNow);

        // Act
        var result = await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        client.CallCount.Should().Be(1); // Should poll because cache is stale
        result.Should().NotBeNull();
    }

    [Fact]
    public async Task GetCurrentAsync_WhenSnapshotUpdaterFailsToUpdateCache_ThrowsInvalidOperationException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        // Cache is empty

        var records = new List<GitHubIssueRecord>
        {
            new(1, "Test Issue", new List<string> { "status:created", "agent:pm" }, FixedNow.AddHours(-1),
                "https://github.com/AskmethatFR/agent-dashboard/issues/1", FixedNow.AddHours(-1), null)
        };
        var client = new FakeGitHubIssuesClient(records);

        // Use a fake updater that doesn't update the cache
        var fakeUpdater = new FakeBoardSnapshotUpdater(cache, shouldUpdateCache: false);
        var reader = BuildReader(cache, client, BuildOptions(), FixedNow, snapshotUpdater: fakeUpdater);

        // Act
        Func<Task> act = async () => await reader.GetCurrentAsync(CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*Snapshot was not updated in cache*");
    }

    // -----------------------------------------------------------------------------

    // -----------------------------------------------------------------------------
    // Constructor Null Check Scenarios
    // -----------------------------------------------------------------------------

    [Fact]
    public void Constructor_WithNullCache_ThrowsArgumentNullException()
    {
        // Arrange
        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var updater = new BoardSnapshotUpdater(new BoardSnapshotCache());
        var options = BuildOptions(pollInterval: TimeSpan.FromMinutes(1));
        var timeProvider = new ManualTimeProvider(FixedNow);

        // Act & Assert
        var act = () => new GitHubBoardReader(null!, client, updater, options.PollInterval, timeProvider, NullLogger);
        act.Should().Throw<ArgumentNullException>(
            "because the cache parameter cannot be null");
    }

    [Fact]
    public void Constructor_WithNullClient_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var updater = new BoardSnapshotUpdater(cache);
        var options = BuildOptions(pollInterval: TimeSpan.FromMinutes(1));
        var timeProvider = new ManualTimeProvider(FixedNow);

        // Act & Assert
        var act = () => new GitHubBoardReader(cache, null!, updater, options.PollInterval, timeProvider, NullLogger);
        act.Should().Throw<ArgumentNullException>(
            "because the client parameter cannot be null");
    }

    [Fact]
    public void Constructor_WithNullSnapshotUpdater_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var options = BuildOptions(pollInterval: TimeSpan.FromMinutes(1));
        var timeProvider = new ManualTimeProvider(FixedNow);

        // Act & Assert
        var act = () => new GitHubBoardReader(cache, client, null!, options.PollInterval, timeProvider, NullLogger);
        act.Should().Throw<ArgumentNullException>(
            "because the snapshotUpdater parameter cannot be null");
    }

    [Fact]
    public void Constructor_WithNullOptions_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var updater = new BoardSnapshotUpdater(cache);
        var timeProvider = new ManualTimeProvider(FixedNow);

        // Act & Assert
        var act = () => new GitHubBoardReader(cache, client, updater, TimeSpan.FromMinutes(10), null!, NullLogger);
        act.Should().Throw<ArgumentNullException>(
            "because the timeProvider parameter cannot be null");
    }

    [Fact]
    public void Constructor_WithNullTimeProvider_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var updater = new BoardSnapshotUpdater(cache);
        var options = BuildOptions(pollInterval: TimeSpan.FromMinutes(1));

        // Act & Assert
        var act = () => new GitHubBoardReader(cache, client, updater, options.PollInterval, null!, NullLogger);
        act.Should().Throw<ArgumentNullException>(
            "because the timeProvider parameter cannot be null");
    }

    [Fact]
    public void Constructor_WithNullLogger_ThrowsArgumentNullException()
    {
        // Arrange
        using var cache = new BoardSnapshotCache();
        var client = new FakeGitHubIssuesClient(Array.Empty<GitHubIssueRecord>());
        var updater = new BoardSnapshotUpdater(cache);
        var options = BuildOptions(pollInterval: TimeSpan.FromMinutes(1));
        var timeProvider = new ManualTimeProvider(FixedNow);

        // Act & Assert
        var act = () => new GitHubBoardReader(cache, client, updater, options.PollInterval, timeProvider, null!);
        act.Should().Throw<ArgumentNullException>(
            "because the logger parameter cannot be null");
    }
    // Helper Methods
    // -----------------------------------------------------------------------------

    private static GitHubPollingOptions BuildOptions(TimeSpan? pollInterval = null)
    {
        return new GitHubPollingOptions
        {
            Token = "test-token",
            RepositoryOwner = "test-owner",
            RepositoryName = "test-repo",
            PollInterval = pollInterval ?? DefaultPollInterval
        };
    }

    private static GitHubBoardReader BuildReader(
        BoardSnapshotCache cache,
        IGitHubIssuesClient client,
        GitHubPollingOptions options,
        DateTimeOffset now,
        IBoardSnapshotUpdater snapshotUpdater = null)
    {
        var timeProvider = new ManualTimeProvider(now);
        var updater = snapshotUpdater ?? new BoardSnapshotUpdater(cache);
        return new GitHubBoardReader(cache, client, updater, options.PollInterval, timeProvider, NullLogger);
    }

    private static BoardSnapshot BuildTestSnapshot(int ticketId = 1)
    {
        var column = new BoardColumn(new BoardColumnId("CREATED"), new BoardColumnLabel("Created"));
        var agent = new Agent(new AgentId("pm"), new AgentName("Project Manager"), new AgentGlyph("PM"), new AgentRole("project-manager"));
        var ticket = TicketSnapshot.Open(
            new TicketId(ticketId),
            column.Id,
            new TicketTitle("Test TicketSnapshot"),
            agent.Id,
            new Retry(0),
            new Age(TimeSpan.Zero),
            thinking: false,
            freshness: TicketFreshness.Neutral);

        return new BoardSnapshot(
            new[] { column },
            new[] { ticket },
            new[] { agent });
    }

    // Manual time provider that allows us to control the current time
    private sealed class ManualTimeProvider : TimeProvider
    {
        private readonly DateTimeOffset _fixedTime;

        public ManualTimeProvider(DateTimeOffset fixedTime)
        {
            _fixedTime = fixedTime;
        }

        public override DateTimeOffset GetUtcNow() => _fixedTime;
    }
}
